# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/11-RKQ1.200928.002-1631956620804-release-keys/RMX1931/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),RMX1931)

endif
